version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NODE_OPTIONS=--max-old-space-size=512
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped