version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      # Use the existing DATABASE_URL from .env file
      - DATABASE_URL=${DATABASE_URL}
      # Add Groq API keys (to be filled in by user)
      - VALIDATION_API_KEY=${VALIDATION_API_KEY}
      - GROQ_API_KEY_1=${GROQ_API_KEY_1}
      - GROQ_API_KEY_2=${GROQ_API_KEY_2}
      - GROQ_API_KEY_3=${GROQ_API_KEY_3}
      - GROQ_API_KEY_4=${GROQ_API_KEY_4}
    volumes:
      # Mount source code for development
      - ./client:/app/client
      - ./server:/app/server
      - ./shared:/app/shared
      # Exclude node_modules from mounting
      - /app/node_modules
      # Mount uploads directory for persistence
      - ./uploads:/app/uploads
    command: npm run dev
    restart: unless-stopped
    networks:
      - panicsense-network

  # Development database service (optional, since we're using Neon DB in the cloud)
  # Uncomment this section if you want to use a local database for development
  # postgres:
  #   image: postgres:15-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - panicsense-network

networks:
  panicsense-network:
    driver: bridge

# Uncomment if using local PostgreSQL
# volumes:
#   postgres-data: