version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: disaster-monitoring-app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      # Groq API Keys - These will be picked up from .env file
      - VALIDATION_API_KEY=${VALIDATION_API_KEY}
      - GROQ_API_KEY_1=${GROQ_API_KEY_1}
      - GROQ_API_KEY_2=${GROQ_API_KEY_2}
      - GROQ_API_KEY_3=${GROQ_API_KEY_3}
      - GROQ_API_KEY_4=${GROQ_API_KEY_4}
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: disaster-monitoring-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: