version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      # Environment variables from .env file
      - DATABASE_URL=${DATABASE_URL}
      - VALIDATION_API_KEY=${VALIDATION_API_KEY}
      - GROQ_API_KEY_1=${GROQ_API_KEY_1}
    volumes:
      # Mount uploads directory for persistence
      - ./uploads:/app/uploads
    restart: unless-stopped