version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NODE_OPTIONS=--max-old-space-size=512
    volumes:
      - ./uploads:/app/uploads
      - ./attached_assets:/app/attached_assets
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s