[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "langdetect>=1.0.9",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
