# SIMPLE RENDER DEPLOYMENT CONFIGURATION
services:
  - type: web
    name: panicsense
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server-deploy.js
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: panicsense-db
          property: connectionString

databases:
  - name: panicsense-db
    plan: free
    region: singapore