services:
  - type: web
    name: disaster-sentiment-analysis
    env: node
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip python3-venv python3-full build-essential
      mkdir -p /usr/share/nltk_data
      python3 -m venv /app/venv
      . /app/venv/bin/activate
      pip install --upgrade pip
      npm ci
      chmod +x render-setup.sh
      ./render-setup.sh
    startCommand: |
      if [ -f dist/wrapper.js ]; then
        NODE_ENV=production node --experimental-modules dist/wrapper.js
      else
        NODE_ENV=production node --experimental-modules dist/index.js
      fi
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: disaster-sentiment-db
          property: connectionString

databases:
  - name: disaster-sentiment-db
    databaseName: disaster_sentiment
    user: disaster_sentiment_user
    plan: free