services:
  - type: web
    name: panicsense
    env: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: node run.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: true
    healthCheckPath: /api/health