# Simple Render configuration that works without TypeScript dependencies
services:
  - type: web
    name: disaster-monitoring-platform
    env: node
    plan: starter
    buildCommand: |
      # Install dependencies
      npm install
      # Build the frontend only
      npx vite build
    # Use our pure CommonJS server implementation directly
    startCommand: NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: disaster-monitoring-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: disaster-monitoring-db
    plan: starter