services:
  - type: web
    name: panicsense-ph
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node pre-render-start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TZ
        value: Asia/Manila
      - key: RUNTIME_ENV
        value: render
      - key: HOST
        value: 0.0.0.0
      - key: PYTHON_SERVICE_ENABLED
        value: true
      - key: ENABLE_SOCIAL_SCRAPER
        value: true
      - key: DISABLE_SSL_VERIFY
        value: true
      - key: DB_SSL_REQUIRED
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: panicsense-db
          property: connectionString

databases:
  - name: panicsense-db
    plan: free