services:
  # A Docker web service
  - type: web
    name: panicsense-ph
    env: docker
    region: singapore  # Choose the appropriate region
    plan: starter      # Or choose another plan based on your needs
    buildCommand: "" # Docker images are pre-built
    startCommand: "./render-setup.sh && npm run startRender" # Run migrations and then start app
    healthCheckPath: /api/health
    dockerfilePath: ./Dockerfile
    numInstances: 1
    autoDeploy: true
    disk:
      name: panicsense-data
      mountPath: /data
      sizeGB: 1
    # Use Postgres as the database
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: panicsense-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: PYTHON_PATH
        value: python3
      - key: SESSION_SECRET
        generateValue: true
      # Add any additional environment variables your application needs
      # For example, if you need OpenAI API key:
      # - key: OPENAI_API_KEY
      #   sync: false # This means it's a secret that you'll set manually

databases:
  # Create a Postgres database
  - type: postgres
    name: panicsense-db
    plan: free
    region: singapore
    postgresMajorVersion: 15
    ipAllowList: [] # Allow all IPs during development