services:
  - type: web
    name: panicsense-ph
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TZ
        value: Asia/Manila
      - key: RUNTIME_ENV
        value: render
      - key: HOST
        value: 0.0.0.0
      - key: DISABLE_SSL_VERIFY
        value: true
      - key: DB_SSL_REQUIRED
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: panicsense-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: panicsense-db
    plan: free