services:
  - type: web
    name: panicsense
    runtime: node
    region: oregon
    plan: free
    buildCommand: bash ./build.sh
    startCommand: node render-start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: panicsense-db
          property: connectionString
      - key: GROQ_API_KEY
        sync: false

databases:
  - name: panicsense-db
    region: oregon
    plan: free
    postgresMajorVersion: 14