# SIMPLE RENDER DEPLOYMENT CONFIGURATION
services:
  - type: web
    name: panicsense
    env: node
    plan: free
    buildCommand: npm install && npx vite build
    startCommand: node server-deploy.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: panicsense-db
          property: connectionString

databases:
  - name: panicsense-db
    plan: free