services:
  # Web service (Node.js frontend)
  - type: web
    name: panicsense-web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: panicsense-db
          property: connectionString

  # Python service (for analysis)
  - type: worker
    name: panicsense-python
    env: python
    buildCommand: pip install -r python/requirements.txt
    startCommand: python python/daemon.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: panicsense-db
          property: connectionString

databases:
  - name: panicsense-db
    plan: free