services:
  - type: web
    name: disaster-monitoring-platform
    env: node
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh
    envVars:
      - key: NODE_ENV
        value: production
      # For using your existing Neon database, add the DATABASE_URL as a secret in Render dashboard
      # - key: DATABASE_URL
      #   sync: false # This will be added manually as a secret
      # If using Render's own managed database instead of Neon, uncomment this section:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: disaster-db
      #     property: connectionString

# If using Render's own managed database instead of Neon, uncomment this section:
# databases:
#   - name: disaster-db
#     databaseName: disasterdb
#     user: disastermonitor
#     plan: free