# render.yaml - Simple configuration for Render deployment with CommonJS fix
services:
  - type: web
    name: disaster-monitoring-platform
    env: node
    plan: starter
    buildCommand: |
      # Install dependencies
      npm install
      # Build the frontend
      npx vite build
      # Make the build.sh script executable
      chmod +x build.sh
      # Run our build script that fixes CommonJS compatibility 
      ./build.sh
    # Use the standard start command to use dist/index.js - now it will be our CommonJS version
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: disaster-monitoring-db
          property: connectionString

databases:
  - name: disaster-monitoring-db
    plan: starter