services:
  - type: web
    name: panic-sense-ph
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run startRender
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEON_DATABASE_URL
        sync: false
      - key: PYTHON_PATH
        value: python3
    
    healthCheckPath: /api/health
    buildFilter:
      paths:
        - client/**
        - server/**
        - shared/**
        - index.js
        - vite.config.ts
        - render-setup.sh
        - Procfile
        - package.json
        - render.yaml
    disk:
      name: data
      mountPath: /data
      sizeGB: 1