# Render Blueprint specification
services:
  - type: web
    name: panicsense
    env: node
    plan: starter
    buildCommand: chmod +x render-deploy.sh && npm install
    startCommand: ./render-deploy.sh
    repo: https://github.com/yourusername/panicsense
    # Uncomment below if using a Render managed database
    # envVars:
    #   - key: DATABASE_URL
    #     fromDatabase:
    #       name: panicsense-db
    #       property: connectionString
    envVars:
      - key: NODE_ENV
        value: production

# Uncomment below if you want Render to create a managed database
# databases:
#   - name: panicsense-db
#     plan: starter