# PRODUCTION RENDER CONFIGURATION FOR FREE TIER
# Uses pure CommonJS server.js implementation with NO top-level await
services:
  - type: web
    name: panicsense-deployment
    env: node
    plan: free
    buildCommand: npm install && npx vite build
    startCommand: NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: panicsense-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: panicsense-db
    plan: free