# PRODUCTION RENDER CONFIGURATION
# Uses pure CommonJS server.js implementation with NO top-level await
services:
  - type: web
    name: disaster-monitoring-platform
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npx vite build
    startCommand: NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: disaster-monitoring-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: disaster-monitoring-db
    region: singapore
    plan: free