# render.yaml - Configuration for Render deployment
services:
  - type: web
    name: disaster-monitoring-platform
    env: node
    plan: starter
    buildCommand: node render-build.js && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: disaster-monitoring-db
          property: connectionString

databases:
  - name: disaster-monitoring-db
    plan: starter