# render.yaml - COMPLETELY REFACTORED FOR RENDER DEPLOYMENT
services:
  - type: web
    name: disaster-monitoring-platform
    env: node
    plan: starter
    # Use our special deployment script that handles everything
    buildCommand: ./render-deploy.sh
    # Use our launcher script that avoids TypeScript completely
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: disaster-monitoring-db
          property: connectionString

databases:
  - name: disaster-monitoring-db
    plan: starter