# render.yaml - Simple configuration for Render deployment
services:
  - type: web
    name: disaster-monitoring-platform
    env: node
    plan: starter
    buildCommand: npm install && npx vite build
    # Use our pure JavaScript file with NO top-level await
    startCommand: NODE_ENV=production node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: disaster-monitoring-db
          property: connectionString

databases:
  - name: disaster-monitoring-db
    plan: starter