version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: disaster-monitoring-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      # Using Neon Database for all environments
      - DATABASE_URL=postgresql://neondb_owner:npg_N5MsSKHuk1Qf@ep-silent-sun-a1u48xwz-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      # Groq API Keys - These will be picked up from .env file
      - VALIDATION_API_KEY=${VALIDATION_API_KEY}
      - GROQ_API_KEY_1=${GROQ_API_KEY_1}
      - GROQ_API_KEY_2=${GROQ_API_KEY_2}
      - GROQ_API_KEY_3=${GROQ_API_KEY_3}
      - GROQ_API_KEY_4=${GROQ_API_KEY_4}
    volumes:
      - nltk_data:/usr/local/share/nltk_data
      - app-data:/app/data
    restart: unless-stopped

volumes:
  nltk_data:
  app-data: