services:
  - type: web
    name: disaster-monitoring-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: /app/start.sh
    healthCheckPath: /
    numInstances: 1
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_N5MsSKHuk1Qf@ep-silent-sun-a1u48xwz-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      # Groq API Keys - Specify secrets in Render Dashboard
      - key: VALIDATION_API_KEY
        sync: false # Set this manually in the Render dashboard
      - key: GROQ_API_KEY_1
        sync: false # Set this manually in the Render dashboard
      - key: GROQ_API_KEY_2
        sync: false # Set this manually in the Render dashboard
      - key: GROQ_API_KEY_3
        sync: false # Set this manually in the Render dashboard
      - key: GROQ_API_KEY_4
        sync: false # Set this manually in the Render dashboard
    autoDeploy: true

# Using external Neon Database instead of provisioning one in Render