name: Deploy to Render

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if different

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}  # Your Render service ID
          api_key: ${{ secrets.RENDER_API_KEY }}  # Your Render API key
          clear_cache: true
          wait_deploy: true
          github_token: ${{ secrets.GITHUB_TOKEN }}